LanType = "EN"
Text_ExpireTime = "Expire time of this version {0} : "
Text_ExpiredNotice = "Expired!"
Text_PotionNotice = "potion cooldown ： {0} / 270   {1} | Count: {2}"
Text_ForceReset = "Force reset battle data"
Text_SupportJobs = "Curr Support Jobs:"
Tab_DeathSentence = "DeathSentence Skill"
Toggle_Pull = "Pull"
Toggle_UsePotion = "UsePotion"
Toggle_Stop = "Stop"
Toggle_Burst = "Burst"
Toggle_AOE = "AOE"
Toggle_DOT = "DOT"
Toggle_TrueNorth = "TrueNorth"
Toggle_FinalBurst = "FinalBurst"
Toggle_AutoDefence = "AutoDefence"
Toggle_UseSong = "UseSong"
Toggle_GCDHeal = "GCD Heal"
Toggle_CrimsonCyclone = "Crimson Cyclone"
Text_HighPrioritySpell = "Cast HighPriority Spells:"
Text_CastSpell = "Cast Spells:"
Text_ScanHotbar = "Scan Hotbar"
Tooltip_ScanHotbar = "If you have modified the hotkey bar, please click this button once"
Text_MaybeNotSupport = "Maybe the current job is not yet supported."
Text_CountDown = "Countdown :"
Text_CountdownFinish = "CountdownFinish"
Text_AIRootStoping = "Stopping"
Text_AIRootNoTarget = "No Target"
Text_AIRootCanAttack = " Target is valid"
Text_LocalTime = "LocalTime :"
Text_BattleTime = "BattleTime "
Button_OpenSetting = "Setting"
Text_AutoReset = "Specify the default value for Toggle after a battle reset"
Tab_General_Base = "Base"
Tab_General_Blacklist = "Dot Blacklist"
Tab_General_Potion = "Potion"
Tab_General_AutoReset = "AutoReset"
Tab_General_TTK = "TTK"
Tab_General_Slide = "Slide"
Tab_General_Macro = "Macro"
Tab_General_Opener = "Opener"
Tab_PhyDps_Bard = "Bard"
Tab_PhyDps_MCH = "Machinist"
Input_AbilityTimesInGCD = "AbilityTimesInGCD"
Input_RegionOfAbility = "RegionOfAbility"
Input_StateSyncDuration = "StateSyncDuration"
Input_AttackRange = "AttackRange"
Toggle_AbilityFirst = "AbilityFirst"
Toggle_AutoInterrupt = "AutoInterrupt"
Toggle_Icon = "Display Icon"
Toggle_AutoTrueNorth = "Auto TrueNorth"
Toggle_ShowMeleePos = "Show Melee Pos Helper"
Toggle_OpenDebugLog = "Open DebugLog"
Toggle_OpenTTK = "Use TTK (time to kill)"
Toggle_OpenSlide = "Open Casting Move Block"
Input_Slide_Time = "Casting Block Time(ms)"
Input_TTK_Time = "TTK check time (ms)"
Input_FinalBurstCheckTime = "FinalBurst check time (ms) :"
Input_TTK_IngoreDamage = "TTK ignore damage:"
Input_OverlayScale = "OverlayScale"
Toggle_AutoPullInCambat = "Open Pull InCambat"
Combo_DexPotion = "DexPotion"
Combo_StrPotion = "StrPotion"
Combo_MindPotion = "MindPotion"
Combo_IntPotion = "IntPotion"
Toggle_Apex = "Apex"
Toggle_Bloodletter = "Bloodletter"
Toggle_Delay1GCD2UseBuffs = "Delay 1GCD to use buffs "
Toggle_ForceApexWaitBuffs = "Force Apex wait buffs "
Input_ApexValue = "Apex Value"
Input_DotTime2Refresh = "DotLeftTime2Refresh"
Toggle_NoBarrageShadowBite = "NoBarrageShadowBite"
Toggle_EarlyEmpyrealArrow = "EarlyEmpyrealArrow"
Input_EarlyEmpyrealArrowTime = "EarlyEmpyrealArrow_Time"
Toggle_Heal = "Heal"
Toggle_AspectedBenefic = "Aspected Benefic"
Toggle_SwiftRes = "SwiftRes"
Toggle_LucidDreaming = "Lucid Dreaming"
Toggle_ThreePartyShieldPull = "PrePullShield3"
Toggle_EarlyDecisionMode = "Early Decision Mode"
Healer_SelectResPrio = "Select Rez Priority"
Toggle_Divination = "Divination"
Toggle_Lightspeed = "Lightspeed"
Toggle_MinorArcana = "Minor Arcana"
Toggle_MAPlay = "Minor Arcana Play"
Toggle_EarthlyStar = "Earthly Star"
Toggle_CelestialOpposition = "Celestial Opposition"
Toggle_EssentialDignity = "EssentialDignity"
Toggle_Exaltation = "Exaltation"
Toggle_CelestialIntersection = "Celestial Intersection"
Toggle_CollectiveUnconscious = "Collective Unconscious"
Toggle_Synastry = "Synastry"
Toggle_Horoscope = "Horoscope"
Text_CardWeight = "Card Weight Prio"
Input_TTK_Aero = "TTK Aero (Dot before kill)"
Text_TanksPrio = "Tanks Prio"
Text_MeleeDpsPrio = "MeleeDps Prio"
Text_PhysRangeDpsPrio = "Phys Range Prio"
Text_MagicalDpsPrio = "Magical Prio"
Text_HealerPrio = "Healer prio"
Input_PldCardWeight = "PLD"
Input_WarCardWeight = "WAR"
Input_DrkCardWeight = "DRK"
Input_GnbCardWeight = "GNB"
Input_MnkCardWeight = "MNK"
Input_DrgCardWeight = "DRG"
Input_NinCardWeight = "NIN"
Input_SamCardWeight = "SAM"
Input_RprCardWeight = "RPR"
Input_BrdCardWeight = "BRD"
Input_MchCardWeight = "MCH"
Input_DncCardWeight = "DNC"
Input_BlmCardWeight = "BLM"
Input_SmnCardWeight = "SMN"
Input_RdmCardWeight = "RDM"
Input_BluCardWeight = "BLU"
Input_WhmCardWeight = "WHM"
Input_SchCardWeight = "SCH"
Input_AstCardWeight = "AST"
Input_SgeCardWeight = "SGE"
Toggle_AspectedHelios = "AspectedHelios"
Toggle_Helios = "Helios"
Toggle_Benefic2 = "Benefic2"
Toggle_Play = "Play"
Toggle_PlayCard = "PlayCard"
Text_healpercentage = "heal percentage"
Toggle_Assize = "Assize"
Toggle_Tetragrammaton = "Tetragrammaton"
Toggle_DivineBenison = "DivineBenison"
Toggle_Aquaveil = "Aquaveil"
Toggle_AfflatusMisery = "AfflatusMisery"
Toggle_AfflatusRapture = "AfflatusRapture"
Toggle_PlenaryIndulgence = "Plenary Indulgence"
Input_TTK_EukrasianDosis = "TTK_EukrasianDosis"
Toggle_Toxikon = "Toxikon"
Tab_Healer_Sage = "Sage"
Tab_Healer_Ast = "AST"
Toggle_BloodWeapon = "Blood Weapon"
Toggle_Delirium = "Delirium"
Toggle_TechFirst = "TechStep Opener"
Toggle_Waltz = "Auto Waltz"
Toggle_Preventoverflow = "Preventoverflow"
Toggle_WildFireFirst = "WildFireFirst"
Input_StrongGCDCheckTime = "StrongGCDCheckTime"
Toggle_Battery = "Battery"
Toggle_UseHarpe = "Use Harpe"
Toggle_GallowPrefer = "Prefer Gallow"
Toggle_GNBRoughDivide = "RoughDivide"
Tab_Tank_GNB = "GunBreaker"
Toggle_DRKPlunge = "Plunge"
Tab_Tank_DRK = "DK"
Toggle_EdgeofShadow = "Edge of Shadow"
Toggle_PLDIntervene = "Intervene"
Tab_Tank_PLD = "PLD"
Toggle_PLDAutoStance = "Auto Stance"
ReserveManaPercentage = "Reserve Mana Percentage"
FightOrFlightTiming = "Fight or Flight timing"
SheltronThreshold = "Sheltron Treshold"
Toggle_Sheltron = "Use Sheltron"
Toggle_IronWill = "Use IronWill"
Toggle_Intervene = "Use Intervene"
Toggle_Requiescat = "Use Requiescat"
Text_Ifrit = "Ifrit"
Text_Titan = "Titan"
Text_Garuda = "Garuda"
Toggle_SummonBurst = "SummonBurst"
Toggle_ChainStratagem = "ChainStratagem"
Toggle_Aetherflow = "Aetherflow"
Tab_MeleeDPS_NIN = "NIN"
Toggle_NIN_TrickAttackTime = "TrickAttackTime"
Toggle_NIN_BurstDelayGCDview = "Hide/Display Burst Delay Setting"
Toggle_NIN_BurstDelayGCD = "Burst Delay GCD In Battle Start"
Toggle_NIN_AutoNinjutsu = "Hide/Display Ninjutsu Setting"
Toggle_NIN_Ninjutsu = "Ninjutsu Setting"
Input_NIN_Suiton = "Suiton"
Input_NIN_Doton = "Doton"
Input_NIN_Huton = "Huton"
Input_NIN_SuitonTime = "SuitonTime(ms)"
Input_NIN_DotonTime = "DotonTime(ms)"
Input_NIN_HutonTime = "HutonTime(ms)"
Input_NIN_EndSuitonTime = "EndSuitonTime(ms)"
Input_NIN_SettingInfo = "Click the previous button after modifying"
Input_NIN_Setting = "There is a setting of what to do when time CountDown"
Btn_NIN_UpdateCountDown = "Update CountDown"
Toggle_NIN_BaseGCDRecastTime = "BaseGCDRecastTime"
Toggle_NIN_BaseGCDRecastTime_Tip = "Base GCD RecastTime will change when use Ninjutsu,Set nothing here is not influence.there is set for using trickAttack after Ninjutsu"
Tip_NIN_TrickAttackTime = "Using TrickAttack when gcd's cooldown less than this time(ms)"
Tip_NIN_ImageBTN_ArmorCrush = "Adjust what spell will be used in the next third combo.When the button is gray, press it again to select another branch.\n Now next the 3rd combo is {0}"
Tip_NIN_BurstDelayGCD = "Burst Delay GCD in battle start"
Toggle_NIN_WithTrickAttack = "WithTrickAttack"
Toggle_AutoPosition = "Auto Position"
Tip_AutoPosition = "if checked ,When the combo has a branching, select according to the current position"
Tip_NIN_WithTrickAttack = "if checked,When the two spell(Trick Attack and the 3rd combo spell) will used for a similar time(about 2120ms),select the combo spell according to the current position"
Toggle_Verraise = "Verraise"
Toggle_PerfectBalance = "PerfectBalance"
Toggle_RiddleofWind = "RiddleofWind"
