LanType = "EN"
Text_ExpireTime = "Expire time of this version {0} : "
Text_ExpiredNotice = "Expired!"
Text_PotionNotice = "potion cooldown ： {0} / 270   {1} | Count: {2}"
Text_ForceReset = "Force reset battle data"
Text_SupportJobs = "Curr Support Jobs:"
Toggle_Pull = "Pull"
Toggle_UsePotion = "UsePotion"
Toggle_Stop = "Stop"
Toggle_Burst = "Burst"
Toggle_AOE = "AOE"
Toggle_DOT = "DOT"
Toggle_TrueNorth = "TrueNorth"
Toggle_FinalBurst = "FinalBurst"
Toggle_UseSong = "UseSong"
Toggle_GCDHeal = "GCD Heal"
Text_HighPrioritySpell = "Cast HighPriority Spells:"
Text_CastSpell = "Cast Spells:"
Text_ScanHotbar = "Scan Hotbar"
Tooltip_ScanHotbar = "If you have modified the hotkey bar, please click this button once"
Text_MaybeNotSupport = "Maybe the current job is not yet supported."
Text_CountDown = "Countdown :"
Text_CountdownFinish = "CountdownFinish"
Text_AIRootStoping = "Stopping"
Text_AIRootNoTarget = "No Target"
Text_AIRootCanAttack = " Target is valid"
Text_LocalTime = "LocalTime :"
Text_BattleTime = "BattleTime "
Button_OpenSetting = "Setting"
Text_AutoReset = "Specify the default value for Toggle after a battle reset"
Tab_General_Base = "Base"
Tab_General_Blacklist = "Dot Blacklist"
Tab_General_Potion = "Potion"
Tab_General_AutoReset = "AutoReset"
Tab_General_TTK = "TTK"
Tab_General_Macro = "Macro"
Tab_General_Opener = "Opener"
Tab_PhyDps_Bard = "Bard"
Tab_PhyDps_MCH = "Machinist"
Input_AbilityTimesInGCD = "AbilityTimesInGCD"
Input_RegionOfAbility = "RegionOfAbility"
Input_StateSyncDuration = "StateSyncDuration"
Input_AttackRange = "AttackRange"
Toggle_AbilityFirst = "AbilityFirst"
Toggle_AutoInterrupt = "AutoInterrupt"
Toggle_AutoTrueNorth = "Auto TrueNorth"
Toggle_ShowMeleePos = "Show Melee Pos Helper"
Toggle_OpenDebugLog = "Open DebugLog"
Toggle_OpenTTK = "Use TTK (time to kill)"
Input_TTK_Time = "TTK check time (ms)"
Input_FinalBurstCheckTime = "FinalBurst check time (ms) :"
Input_TTK_IngoreDamage = "TTK ignore damage:"
Input_OverlayScale = "OverlayScale"
Combo_DexPotion = "DexPotion"
Combo_StrPotion = "StrPotion"
Combo_MindPotion = "MindPotion"
Combo_IntPotion = "IntPotion"
Toggle_Apex = "Apex"
Toggle_Bloodletter = "Bloodletter"
Toggle_Delay1GCD2UseBuffs = "Delay 1GCD to use buffs "
Toggle_ForceApexWaitBuffs = "Force Apex wait buffs "
Input_ApexValue = "Apex Value"
Input_DotTime2Refresh = "DotLeftTime2Refresh"
Toggle_NoBarrageShadowBite = "NoBarrageShadowBite"
Toggle_EarlyEmpyrealArrow = "EarlyEmpyrealArrow"
Input_EarlyEmpyrealArrowTime = "EarlyEmpyrealArrow_Time"
Toggle_Heal = "Heal"
Toggle_AspectedBenefic = "Aspected Benefic"
Toggle_SwiftRes = "SwiftRes"
Toggle_LucidDreaming = "Lucid Dreaming"
Toggle_ThreePartyShieldPull = "PrePullShield3"
Toggle_EarlyDecisionMode = "Early Decision Mode"
Healer_SelectResPrio = "Select Rez Priority"
Input_TTK_EukrasianDosis = "TTK_EukrasianDosis"
Tab_Healer_Sage = "Sage"
Toggle_TechFirst = "TechStep Opener"
Toggle_WildFireFirst = "WildFireFirst"
Input_StrongGCDCheckTime = "StrongGCDCheckTime"
Toggle_UseHarpe = "Use Harpe"
Toggle_GallowPrefer = "Prefer Gallow"
Toggle_GNBRoughDivide = "RoughDivide"
Tab_Tank_GNB = "GunBreaker"
