LanType = "CN"
Text_ExpireTime = "当前版本过期时间（UTC） {0} : "
Text_ExpiredNotice = "版本已经过期!"
Text_PotionNotice = "爆发药冷却计时 ： {0} / 270   {1} | 数量: {2}"
Text_ForceReset = "强制重置战斗数据"
Text_SupportJobs = "当前支持职业 :"
Toggle_Pull = "主动攻击"
Toggle_UsePotion = "使用爆发药"
Toggle_Stop = "停手"
Toggle_Burst = "爆发"
Toggle_AOE = "AOE"
Toggle_DOT = "DOT"
Toggle_TrueNorth = "真北"
Toggle_FinalBurst = "最终爆发"
Toggle_TechFirst = "大舞起手"
Text_HighPrioritySpell = "强制使用高优先级技能(下一个窗口期生效) :"
Text_CastSpell = "强制使用技能(下一个窗口期生效):"
Text_ScanHotbar = "扫描热键栏"
Tooltip_ScanHotbar = "如果你刚才修改了热键栏，请点击一次"
Text_MaybeNotSupport = "也许当前职业还未得到支持."
Text_CountDown = "倒计时 :"
Text_CountdownFinish = "倒计时结束"
Text_AIRootStoping = "停手中"
Text_AIRootNoTarget = "没有目标"
Text_AIRootCanAttack = " 目标有效"
Text_LocalTime = "本地时间 "
Text_BattleTime = "战斗时间 "
Button_OpenSetting = "设置界面"
Text_AutoReset = "设置战斗重置时一些按钮的默认状态"
Tab_General_Base = "基本"
Tab_General_Blacklist = "Dot黑名单"
Tab_General_Potion = "爆发药"
Tab_General_AutoReset = "自动重置"
Tab_PhyDps_Bard = "诗人"
Input_AbilityTimesInGCD = "GCD内能力技数量"
Input_RegionOfAbility = "能力技能窗口期"
Toggle_AbilityFirst = "强制使用的技能优先级最高"
Toggle_AutoInterrupt = "自动打断"
Toggle_OpenDebugLog = "开启Debug日志"
Combo_DexPotion = "巧力"
Combo_StrPotion = "刚力"
Combo_MindPotion = "意力"
Combo_IntPotion = "智力"
Toggle_Apex = "绝峰箭"
Toggle_Bloodletter = "失血箭"
Toggle_Delay1GCD2UseBuffs = "起手爆发的双Buff延迟1个GCD"
Toggle_ForceApexWaitBuffs = "强制爆破箭等待爆发期"
Input_ApexValue = "使用绝峰时的能量"
Input_DotTime2Refresh = "检测是否需要刷新DOT的剩余时间"
Toggle_Heal = "Heal"
Toggle_SwiftRes = "SwiftRes"
Toggle_LucidDreaming = "醒梦"
Toggle_ThreePartyShieldPull = "起手刷盾"
Toggle_UseSong = "使用歌曲"
Toggle_GCDHeal = "GCD治疗"
Tab_General_TTK = "TTK"
Tab_General_Macro = "宏"
Tab_General_Opener = "起手"
Tab_PhyDps_MCH = "机工"
Input_StateSyncDuration = "状态同步延时"
Input_AttackRange = "攻击范围"
Toggle_AutoTrueNorth = "自动真北"
Toggle_ShowMeleePos = "显示身位指示器"
Toggle_OpenTTK = "开启TTK"
Input_TTK_Time = "TTK 检测时间 (ms)"
Input_FinalBurstCheckTime = "最终爆发检测时间 (ms) :"
Input_TTK_IngoreDamage = "TTK 忽略的伤害值:"
Input_OverlayScale = "Overlay缩放"
Toggle_NoBarrageShadowBite = "不使用纷乱影噬箭"
Toggle_EarlyEmpyrealArrow = "提前计算九天"
Input_EarlyEmpyrealArrowTime = "提前计算九天的时间"
Toggle_AspectedBenefic = "Aspected Benefic"
Toggle_EarlyDecisionMode = "提前决策模式"
Healer_SelectResPrio = "Select Rez Priority"
Input_TTK_EukrasianDosis = "TTK_EukrasianDosis"
Tab_Healer_Sage = "贤者"
Toggle_WildFireFirst = "野火优先"
Input_StrongGCDCheckTime = "高威力GCD等待时间"
Toggle_UseHarpe = "勾刃"
Toggle_GallowPrefer = "优先背身位"
Toggle_GNBRoughDivide = "RoughDivide"
Tab_Tank_GNB = "GunBreaker"
