LanType = "CN"
Text_ExpireTime = "当前版本过期时间（UTC） {0} : "
Text_ExpiredNotice = "版本已经过期!"
Text_PotionNotice = "爆发药冷却计时 ： {0} / 270   {1} | 数量: {2}"
Text_ForceReset = "强制重置战斗数据"
Text_SupportJobs = "当前支持职业 :"
Toggle_Pull = "主动攻击"
Toggle_UsePotion = "使用爆发药"
Toggle_Stop = "停手"
Toggle_Burst = "爆发"
Toggle_AOE = "AOE"
Toggle_DOT = "DOT"
Toggle_TrueNorth = "真北"
Toggle_FinalBurst = "最终爆发"
Toggle_TechFirst = "大舞起手"
Text_HighPrioritySpell = "强制使用高优先级技能(下一个窗口期生效) :"
Text_CastSpell = "强制使用技能(下一个窗口期生效):"
Text_ScanHotbar = "扫描热键栏"
Tooltip_ScanHotbar = "如果你刚才修改了热键栏，请点击一次"
Text_MaybeNotSupport = "也许当前职业还未得到支持."
Text_CountDown = "倒计时 :"
Text_CountdownFinish = "倒计时结束"
Text_AIRootStoping = "停手中"
Text_AIRootNoTarget = "没有目标"
Text_AIRootCanAttack = " 目标有效"
Text_LocalTime = "本地时间 "
Text_BattleTime = "战斗时间 "
Button_OpenSetting = "设置界面"
Text_AutoReset = "设置战斗重置时一些按钮的默认状态"
Tab_General_Base = "基本"
Tab_General_Blacklist = "Dot黑名单"
Tab_General_Potion = "爆发药"
Tab_General_AutoReset = "自动重置"
Tab_PhyDps_Bard = "诗人"
Input_AbilityTimesInGCD = "GCD内能力技数量"
Input_RegionOfAbility = "能力技能窗口期"
Toggle_AbilityFirst = "强制使用的技能优先级最高"
Toggle_AutoInterrupt = "自动打断"
Toggle_OpenDebugLog = "开启Debug日志"
Combo_DexPotion = "巧力"
Combo_StrPotion = "刚力"
Combo_MindPotion = "意力"
Combo_IntPotion = "智力"
Toggle_Apex = "绝峰箭"
Toggle_Bloodletter = "失血箭"
Toggle_Delay1GCD2UseBuffs = "起手爆发的双Buff延迟1个GCD"
Toggle_ForceApexWaitBuffs = "强制爆破箭等待爆发期"
Input_ApexValue = "使用绝峰时的能量"
Input_DotTime2Refresh = "检测是否需要刷新DOT的剩余时间"
Toggle_Heal = "Heal"
Toggle_SwiftRes = "SwiftRes"
Toggle_LucidDreaming = "醒梦"
Toggle_ThreePartyShieldPull = "起手刷盾"
Toggle_UseSong = "使用歌曲"
Toggle_GCDHeal = "GCD治疗"
Tab_General_TTK = "TTK"
Tab_General_Macro = "宏"
Tab_General_Opener = "起手"
Tab_PhyDps_MCH = "机工"
Input_StateSyncDuration = "状态同步延时"
Input_AttackRange = "攻击范围"
Toggle_AutoTrueNorth = "自动真北"
Toggle_ShowMeleePos = "显示身位指示器"
Toggle_OpenTTK = "开启TTK"
Input_TTK_Time = "TTK 检测时间 (ms)"
Input_FinalBurstCheckTime = "最终爆发检测时间 (ms) :"
Input_TTK_IngoreDamage = "TTK 忽略的伤害值:"
Input_OverlayScale = "Overlay缩放"
Toggle_NoBarrageShadowBite = "不使用纷乱影噬箭"
Toggle_EarlyEmpyrealArrow = "提前计算九天"
Input_EarlyEmpyrealArrowTime = "提前计算九天的时间"
Toggle_AspectedBenefic = "吉星相位"
Toggle_EarlyDecisionMode = "提前决策模式"
Healer_SelectResPrio = "复活优先级"
Input_TTK_EukrasianDosis = "TTK_EukrasianDosis"
Tab_Healer_Sage = "贤者"
Toggle_WildFireFirst = "野火优先"
Input_StrongGCDCheckTime = "高威力GCD等待时间"
Toggle_UseHarpe = "勾刃"
Toggle_GallowPrefer = "优先背身位"
Toggle_GNBRoughDivide = "RoughDivide"
Tab_Tank_GNB = "GunBreaker"
Toggle_Divination = "占卜"
Toggle_Lightspeed = "光速"
Toggle_Waltz = "华尔兹"
Toggle_ChainStratagem = "连环计"
Toggle_Aetherflow = "以太超流"
Toggle_Assize = "法令"
Toggle_AspectedHelios = "阳星相位"
Toggle_MinorArcana = "小奥秘卡"
Toggle_MAPlay = "出小奥秘"
Toggle_EarthlyStar = "地星"
Toggle_CelestialOpposition = "天星冲日"
Toggle_EssentialDignity = "先天禀赋"
Toggle_Exaltation = "擢升"
Toggle_CelestialIntersection = "天星交错"
Toggle_CollectiveUnconscious = "命运之轮"
Toggle_Synastry = "星位合图"
Toggle_Horoscope = "天宫图"
Text_CardWeight = "发卡优先级"
Input_TTK_Aero = "TTK Aero (Dot before kill)"
Text_TanksPrio = "坦克优先级"
Text_MeleeDpsPrio = "近战优先级"
Text_PhysRangeDpsPrio = "远敏优先级"
Text_MagicalDpsPrio = "法系优先级"
Text_HealerPrio = "治疗优先级"
Toggle_Helios = "阳星"
Toggle_Benefic2 = "福星"
Input_PldCardWeight = "PLD"
Input_WarCardWeight = "WAR"
Input_DrkCardWeight = "DRK"
Input_GnbCardWeight = "GNB"
Input_MnkCardWeight = "MNK"
Input_DrgCardWeight = "DRG"
Input_NinCardWeight = "NIN"
Input_SamCardWeight = "SAM"
Input_RprCardWeight = "RPR"
Input_BrdCardWeight = "BRD"
Input_MchCardWeight = "MCH"
Input_DncCardWeight = "DNC"
Input_BlmCardWeight = "BLM"
Input_SmnCardWeight = "SMN"
Input_RdmCardWeight = "RDM"
Input_BluCardWeight = "BLU"
Input_WhmCardWeight = "WHM"
Input_SchCardWeight = "SCH"
Input_AstCardWeight = "AST"
Input_SgeCardWeight = "SGE"
Toggle_Preventoverflow = "防止溢出"
Tab_MeleeDPS_NIN = "忍者"
Toggle_NIN_TrickAttackTime = "背刺时间(ms)"
Toggle_NIN_BurstDelayGCDview = "显示/隐藏开局爆发延后"
Toggle_NIN_BurstDelayGCD = "爆发延后GCD设置"
Toggle_NIN_AutoNinjutsu = "显示/隐藏倒计时忍术"
Toggle_NIN_Ninjutsu = "倒计时忍术设置"
Input_NIN_Suiton = "水遁"
Input_NIN_Doton = "土遁"
Input_NIN_Huton = "风遁"
Input_NIN_SuitonTime = "水遁时间(ms)"
Input_NIN_DotonTime = "土遁时间(ms)"
Input_NIN_HutonTime = "风遁时间(ms)"
Input_NIN_EndSuitonTime = "水遁结束时间(ms)"
Input_NIN_SettingInfo = "修改后请点击前面的按钮"
Input_NIN_Setting = "倒计时结忍术"
Btn_NIN_UpdateCountDown = "更新倒计时设置"
Toggle_NIN_BaseGCDRecastTime = "基础GCD复唱时间"
Toggle_NIN_BaseGCDRecastTime_Tip = "使用忍术后基础复唱时间会变，这里不设置也没有影响。设置这里只是为了使用忍术后能很好的使用背刺"
Tip_NIN_TrickAttackTime = "GCD剩余多少时间才打背刺"
Toggle_AutoPullInCambat ="战斗状态下主动攻击"
Tip_NIN_ImageBTN_ArmorCrush = "调整下一次第三连击使用技能。按钮灰色的时候再按一下选择另一分支。\n现在下一次第三连击用{0}"
Tip_NIN_BurstDelayGCD = "开场延后爆发GCD"
Toggle_NIN_WithTrickAttack = "背刺身位选择"
Toggle_AutoPosition = "自动身位"
Toggle_PlayCard = "发卡"
Tip_AutoPosition = "第三连击根据身位选择"
Tip_NIN_WithTrickAttack  = "背刺时间和第三连击时间相近时,按身位选择第三连击"
Tab_General_Slide = "滑步"
Toggle_OpenSlide = "开启滑步锁定"
Input_Slide_Time = "滑步点(ms)"
Toggle_AutoDefence = "自动减伤"
Toggle_Icon = "显示图标"
Toggle_Delirium = "血乱"
Toggle_BloodWeapon = "嗜血"
Toggle_Play = "好了就发"
Toggle_Verraise = "赤复活"
Toggle_EdgeofShadow = "暗影峰"
Toggle_SummonBurst = "蛮神爆发"
Toggle_Tetragrammaton = "神名"
Toggle_DivineBenison = "神祝祷"
Toggle_Aquaveil = "水流幕"
Text_healpercentage = "治疗百分比"
Toggle_AfflatusMisery = "红花"
Toggle_AfflatusRapture = "兰花"
Toggle_PerfectBalance = "震脚"
Toggle_RiddleofWind = "疾风极意"
Toggle_PlenaryIndulgence = "全大赦"